In [15]:
#TASK 1
import numpy as np

A = np.random.rand(5)
B = np.random.rand(3,3)
C = np.random.rand(2,4)
D = np.random.rand(4,2)
E = np.random.rand(5,5)
F = np.random.rand(5)
G = np.random.rand(3,3)
H = np.random.rand(2,4)
I = np.random.rand(4,2)
J = np.random.rand(5,5)

# Single Array
np.sqrt(A)
np.square(A)
np.log10(F)
np.tan(J)
np.cumsum(G)
np.mean(C) 
np.std(G) 
np.var(D)
np.copysign(C,-3)
np.rint(E)  
np.arccos(I)
np.diag(G)

# Same size Array
np.maximum(A,F) 
np.subtract(D,I) 
np.add(B,G)
np.minimum(B,G)
np.power(B,G) 

# Different size Array
np.multiply(D,C.T) 
np.divide(I,H.T) 

print('Single Array')

print("1"),print(np.sqrt(A))
print('\n--------\n')

print("2"),print(np.square(A))
print('\n--------\n')

print("3"),print(np.log10(F))
print('\n--------\n')

print("4"),print(np.tan(J))
print('\n--------\n')

print("5"),print(np.cumsum(G))
print('\n--------\n')

print("6"),print(np.mean(C))
print('\n--------\n')

print("7"),print(np.std(G))
print('\n--------\n')

print("8"),print(np.var(D))
print('\n--------\n')

print("9"),print(np.copysign(C,-3))
print('\n--------\n')

print("10"),print(np.rint(E))
print('\n--------\n')

print("11"),print(np.arccos(I))
print('\n--------\n')

print("12"),print(np.diag(G))
print('\n--------\n')

print('Same Size Array')

print("13"),print(np.maximum(A,F))
print('\n--------\n')

print("14"),print(np.subtract(D,I))
print('\n--------\n')

print("15"),print(np.add(B,G))
print('\n--------\n')

print("16"),print(np.minimum(B,G))
print('\n--------\n')

print("17"),print(np.power(B,G))
print('\n--------\n')

print('Different Size Array')

print("18"),print(np.dot(C,D))
print('\n--------\n')

print("19"),print(np.multiply(D,C.T))
print('\n--------\n')

print("20"),print(np.divide(I,H.T))

Single Array
1
[0.62559907 0.3341458  0.98363862 0.72302959 0.78749339]

--------

2
[0.15317376 0.01246649 0.93614321 0.27329034 0.38458085]

--------

3
[-0.12898002 -0.0431462  -1.05214643 -0.07681088 -0.20281749]

--------

4
[[0.25778301 0.27242743 0.47770344 1.22656149 0.3182994 ]
 [0.01985091 0.07813025 0.53912208 0.29121541 0.73053676]
 [0.53822043 0.81885878 0.12080807 0.98850247 0.52216998]
 [0.96175551 0.1301693  0.00796949 0.76512126 0.8464895 ]
 [0.82899422 0.70783962 0.8380306  0.58209232 0.96215664]]

--------

5
[0.89954399 1.14664341 1.49911068 1.85079217 2.64115701 3.5513985
 4.2479901  4.47230409 4.52013298]

--------

6
0.5612695091076709

--------

7
0.30532913503342357

--------

8
0.05706548356806967

--------

9
[[-0.39767435 -0.18810934 -0.82584844 -0.04471113]
 [-0.71218514 -0.97075509 -0.70753021 -0.64334237]]

--------

10
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1.]]

--------

11
[[1.15359084 0.92515546]
 [0.534

(None, None)